import { Product } from "./product";

export const PRODUCTS: Product[] = [
  {
    id: 1,
    img: "",
    brand: "Acer",
    model: "V10",
    price: 8000,
    discount: 5,
    rate: 3,
    cpu: "Intel Core i3",
    gpu: "Radeon 500",
    hdd: "1T",
    ram: 8,
    screensize: 15.6,
    os: "Windows",
    description: "here has to be description",
    popular: 50
  },
  {
    id: 2,
    img: "",
    brand: "Lenovo",
    model: "Lx12",
    price: 10000,
    discount: 0,
    rate: 3,
    cpu: "Intel Core i5",
    gpu: "Radeon R5",
    hdd: "256Gb",
    ram: 8,
    screensize: 15.6,
    os: "None",
    description: "here has to be description",
    popular: 44
  },
  {
    id: 3,
    img: "",
    brand: "HP",
    model: "DV6",
    price: 12000,
    discount: 20,
    rate: 5,
    cpu: "Intel Core i3",
    gpu: "Radeon R7",
    hdd: "512Gb",
    ram: 16,
    screensize: 17.3,
    os: "Linux",
    description: "here has to be description",
    popular: 10
  },
  {
    id: 4,
    img: "",
    brand: "Toshiba",
    model: "T23",
    price: 15000,
    discount: 0,
    rate: 4,
    cpu: "Intel Celeron",
    gpu: "GeForce GTX 1050",
    hdd: "2T",
    ram: 16,
    screensize: 15.6,
    os: "Linux",
    description: "here has to be description",
    popular: 67
  },
  {
    id: 5,
    img: "",
    brand: "MSI",
    model: "M64",
    price: 18000,
    discount: 10,
    rate: 5,
    cpu: "Intel Core i7",
    gpu: "GeForce MX110",
    hdd: "2T",
    ram: 32,
    screensize: 17.3,
    os: "Windows",
    description: "here has to be description",
    popular: 75
  },
  {
    id: 6,
    img: "",
    brand: "HP",
    model: "DV5",
    price: 8000,
    discount: 0,
    rate: 3,
    cpu: "Intel Pentium",
    gpu: "Radeon R5",
    hdd: "128Gb",
    ram: 4,
    screensize: 15.6,
    os: "Windows",
    description: "here has to be description",
    popular: 20
  },
  {
    id: 7,
    img: "",
    brand: "Acer",
    model: "E5",
    price: 11000,
    discount: 0,
    rate: 3,
    cpu: "AMD A4",
    gpu: "Radeon 500",
    hdd: "512Gb",
    ram: 8,
    screensize: 15.6,
    os: "Windows",
    description: "here has to be description",
    popular: 15
  },
  {
    id: 8,
    img: "",
    brand: "Asus",
    model: "V56n",
    price: 18000,
    discount: 5,
    rate: 4.5,
    cpu: "Intel Core i7",
    gpu: "GeForce GTX 1660",
    hdd: "2T",
    ram: 16,
    screensize: 15.6,
    os: "Windows",
    description: "here has to be description",
    popular: 80
  },
  {
    id: 9,
    img: "",
    brand: "Acer",
    model: "E1",
    price: 14000,
    discount: 0,
    rate: 4,
    cpu: "Intel Pentium",
    gpu: "GeForce GTX 1050",
    hdd: "1T",
    ram: 12,
    screensize: 15.6,
    os: "Windows",
    description: "here has to be description",
    popular: 60
  },
  {
    id: 10,
    img: "",
    brand: "Lenovo",
    model: "IdeaPad 330",
    price: 23000,
    discount: 0,
    rate: 4,
    cpu: "Intel Core i7",
    gpu: "GeForce GTX 1660",
    hdd: "512Gb",
    ram: 24,
    screensize: 15.6,
    os: "Windows",
    description: "here has to be description",
    popular: 70
  },
  {
    id: 11,
    img: "",
    brand: "Asus",
    model: "ZenBook S13",
    price: 35000,
    discount: 0,
    rate: 5,
    cpu: "AMD A8",
    gpu: "GeForce GTX 1660",
    hdd: "2T",
    ram: 32,
    screensize: 17.3,
    os: "Windows",
    description: "here has to be description",
    popular: 70
  },
  {
    id: 12,
    img: "",
    brand: "HP",
    model: "NoteBook 15",
    price: 13000,
    discount: 5,
    rate: 2.5,
    cpu: "Intel Celeron",
    gpu: "GeForce MX230",
    hdd: "256Gb",
    ram: 4,
    screensize: 15.6,
    os: "None",
    description: "here has to be description",
    popular: 10
  },
  {
    id: 13,
    img: "",
    brand: "HP",
    model: "Pavillion",
    price: 14000,
    discount: 0,
    rate: 1,
    cpu: "Intel Celeron",
    gpu: "GeForce MX230",
    hdd: "256Gb",
    ram: 6,
    screensize: 15.6,
    os: "Windows",
    description: "here has to be description",
    popular: 10
  },
  {
    id: 14,
    img: "",
    brand: "MSI",
    model: "PS42",
    price: 19000,
    discount: 1,
    rate: 5,
    cpu: "Intel Core i7",
    gpu: "GeForce MX230",
    hdd: "1T",
    ram: 16,
    screensize: 17.3,
    os: "Windows",
    description: "here has to be description",
    popular: 90
  },
  {
    id: 15,
    img: "",
    brand: "Dell",
    model: "Inspiron 15",
    price: 11000,
    discount: 0,
    rate: 4,
    cpu: "Intel Core i3",
    gpu: "Radeon 500",
    hdd: "1T",
    ram: 8,
    screensize: 15.6,
    os: "Linux",
    description: "here has to be description",
    popular: 60
  }
];
